config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions'
	}

	resources :abstracts
	root 'staticpages#index'
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :author, presence: true
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  has_many :abstracts, dependent: :destroy
end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_abstract, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @abstracts = @user.abstracts.order(created_at: 'desc')
  end

  def new
    @abstract = Abstract.new
  end

  def show

  end

  def edit

  end

  def create
    @abstract = Abstract.new(abstract_params)
    @abstract.user_id = current_user.id
    if @abstract.save
      redirect_to @abstract, notice: 'あぶすとを投稿しました'
    else
      render :new, alert: 'あぶすとの投稿に失敗しました'
    end
  end

  def update
    if @abstract.update(abstract_params)
      redirect_to @abstract, notice: 'あぶすとを更新しました'
    else
      render :edit, alert: 'あぶすとの更新に失敗しました'
    end
  end

  def destroy
    if @abstract.destroy
      redirect_to root_path, notice: 'あぶすとを削除しました'
    else
      redirect_to root_path, notice: 'あぶすとの削除に失敗しました'
    end
  end

  private

  def find_abstract
    @abstract = Abstract.find(params[:id])
  end

  # Strong Parameter
  def abstract_params
    params.require(:abstract).permit(:title, :author, :doi, :body)
  end

  # 他のユーザーのあぶすとにはアクセスできないようにする
  def validate_user
    if @abstract.user != current_user
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
	# before_action :configure_sign_up_params, only: [:create]
	# before_action :configure_account_update_params, only: [:update]

	# GET /resource/sign_up
	# def new
	#   super
	# end

	# POST /resource
	# def create
	#	super
	# end

	# GET /resource/edit
	# def edit
	#   super
	# end

	# PUT /resource
	# def update
	#   super
	# end

	# DELETE /resource
	# def destroy
	#   super
	# end

	# GET /resource/cancel
	# Forces the session data which is usually expired after sign
	# in to be expired now. This is useful if the user wants to
	# cancel oauth signing in/up in the middle of the process,
	# removing all OAuth session data.
	# def cancel
	#   super
	# end

	# protected

	# If you have extra params to permit, append them to the sanitizer.
	# def configure_sign_up_params
	#   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
	# end

	# If you have extra params to permit, append them to the sanitizer.
	# def configure_account_update_params
	#   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
	# end

	# The path used after sign up.
	# def after_sign_up_path_for(resource)
	#   super(resource)
	# end

	# The path used after sign up for inactive accounts.
	# def after_inactive_sign_up_path_for(resource)
	#   super(resource)
	# end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def bootstrap_alert(key)
		case key
		when "alert"
			"warning"
		when "notice"
			"success"
		when "error"
			"danger"
		end
	end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/abstracts/_form.html.erb
<%= form_for abstract do |f| %>
	<div class="form-group">
		<%= f.label :title, 'タイトル' %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :author, '著者' %>
		<%= f.text_field :author, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :doi, 'DOI' %>
		<%= f.text_field :doi, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :body, 'あぶすと' %>
		<%= f.text_area :body, rows: 10, class: 'form-control' %>
	</div>
	<%= f.submit '投稿', class: 'btn btn-success' %>
<% end %>

app/views/abstracts/edit.html.erb
<div class="container">
	<main>
		<section class="py-5">
			<h1 class="text-center mb-5">編集</h1>
			<%= render 'form', abstract:@abstract %>
		</section>
	</main>
</div>

app/views/abstracts/index.html.erb
<div class="container">
	<main>
		<section class="py-5">
			<h2 class="text-center mb-5">マイページ</h2>
			<div class="row">
				<div class="table-responsive col-sm-12 col-md-4 mb-3 overflow-hidden">
					<h5 class="text-center">基本情報</h5>
					<table class="table">
						<tr>
							<th class="text-nowrap">メールアドレス</th>
							<td><%= @user.email %></td>
						</tr>
						<tr>
							<th class="text-nowrap">投稿したあぶすと</th>
							<td><%= @abstracts.size %></td>
						</tr>
					</table>
					<%= link_to '運営にコンタクト', "/", class: "btn btn-info w-100 mb-2 disabled" %>
					<%= link_to 'ログアウト', destroy_user_session_path, class: "btn btn-warning w-100 mb-2", method: :delete %>
					<%= link_to 'アカウント削除', "/users", class: "btn btn-danger w-100 mb-2", method: :delete, data: {confirm: '本当に削除しますか?'} %>
				</div>

				<div class="col-sm-12 col-md-8">
					<%= link_to '新規投稿', new_abstract_path, class: "btn btn-primary w-100 mb-5" %>

					<h5 class="text-center">投稿したあぶすと</h5>
					<div class="table-responsive">
						<table class="table">
							<thead class="thead-dark">
							<tr>
								<th class="text-nowrap">Title</th>
								<th class="text-nowrap">Author</th>
								<th class="text-nowrap">DOI</th>
							</tr>
							</thead>
							<% if @abstracts.any? %>
								<% @abstracts.each do |abstract| %>
									<tr>
										<td class="w-60 overflow-hidden"><%= link_to abstract.title, abstract %></td>
										<td class="w-20 overflow-hidden"><%= abstract.author %></td>
										<td class="w-20 overflow-hidden"><%= abstract.doi %></td>
									</tr>
								<% end %>
							<% else %>
								<tr>
									<td colspan="5" class="text-nowrap text-info text-center">まだ、あぶすとを投稿していません</td>
								</tr>
							<% end %>
						</table>
					</div> <!-- table-responsive -->
				</div>
			</div>
		</section>
	</main>
</div>

app/views/abstracts/new.html.erb
<div class="container">
	<main>
		<section class="py-5">
			<h1 class="text-center mb-5">新規投稿</h1>
			<%= render 'form', abstract:@abstract %>
		</section>
	</main>
</div>

app/views/abstracts/show.html.erb
<div class="container">
	<main>
		<section class="py-5">
			<h1 class="text-center mb-5"><%= @abstract.title %></h1>
			<h2 class="text-left">基本情報</h2>
			<dl class="row">
				<dt class="col-sm-3">著者</dt>
				<dt class="col-sm-9"><%= @abstract.author %></dt>

				<dt class="col-sm-3">DOI</dt>
				<dt class="col-sm-9"><%= @abstract.doi %></dt>

				<dt class="col-sm-3">作成日</dt>
				<dt class="col-sm-9"><%= @abstract.created_at.strftime('%Y/%m/%d') %></dt>

				<dt class="col-sm-3">更新日</dt>
				<dt class="col-sm-9"><%= @abstract.updated_at.strftime('%Y/%m/%d') %></dt>
			</dl>
			<h2 class="text-left">あぶすと</h2>
			<p>
				<%= simple_format @abstract.body %>
			</p>
			<%= link_to '編集', edit_abstract_path(@abstract), class: "btn btn-primary" %>
			<%= link_to '削除', abstract_path(@abstract), method: :delete, class: "btn btn-danger", data: {confirm: '削除しますか?'} %>
		</section>
	</main>
</div>

app/views/layouts/_header.html.erb
<header>
	<div class="container">
		<nav class="navbar navbar-expand-sm navbar-light">

			<a class="navbar-brand" href="/">
				<i class="fas fa-book"></i>
				あぶすと
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="menu">
				<div class="navbar-nav">
					<% if user_signed_in? %>
						<%= link_to 'マイページ', 'abstracts#index', class: "nav-item nav-link", method: :get %>
						<%= link_to 'ログアウト', destroy_user_session_path, class: "nav-item nav-link", method: :delete %>
						<span class="navbar-text"><%= current_user.email %>さんがログイン中</span>
					<% else %>
						<%= link_to '新規登録', new_user_registration_path, class: "nav-item nav-link", method: :get %>
						<%= link_to 'ログイン', new_user_session_path, class: "nav-item nav-link", method: :get %>
					<% end %>
				</div>
			</div>

		</nav>
	</div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= bootstrap_alert(key) %>">
		<strong>
			<%= value %>
		</strong>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<title>あぶすと</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<%= render 'layouts/messages' %>
	</div>

	<%= yield %>

	<footer class="text-center text-muted py-4">
		Copyright &copy; 2019 abst.science
	</footer>
</body>
</html>

app/views/staticpages/index.html.erb
<header>
	<div class="text-center py-5 cover">
		<h1 class="container display-sm-1 display-lg-4 h-50 py-2">あぶすと</h1>
		<h4 class="container text-center py-2">
			論文を自分なりにまとめることができるメモサービス
		</h4>
		<% if user_signed_in? %>
			<%= link_to 'マイページ', 'abstracts#index', class: "btn btn-info mt-2", method: :get %>
			<%= link_to 'ログアウト', destroy_user_session_path, class: "btn btn-warning mt-2", method: :delete %>
		<% else %>
			<%= link_to '新規登録', new_user_registration_path, class: "btn btn-primary mt-2", method: :get %>
			<%= link_to 'ログイン', new_user_session_path, class: "btn btn-danger mt-2", method: :get %>
		<% end %>
	</div>
</header>
<div class="container">
	<main>
		<style>
			.cover {
				background: url(/images/bg30.jpg);
				background-size: cover;
			}
		</style>
		<section class="py-5 bg-white">
			<div class="container">
				<div class="mb-5 row">
					<div class="col-12 col-md-8 order-sm-1">
						<h3>何度も論文を読みたいですか？</h3>
						<p>
							論文を読むのは大変ではないでしょうか。辞書を片手に、何ページにも及ぶ論文を読み込む作業は、誰しも好きではないと思います。<br>
							しかし、自分の研究に直結するような先行研究の論文があれば、きっちり読み込まなければいけない。しかも、そういった論文は何本もある。<br>
							一度読み込んだ論文でさえ、数カ月もすれば、「あの実験の結果って、どの論文のどこに書いてあったっけ？」となってしまうこともしばしば。<br>
							しかし、あぶすとを使えば、自分なりにその論文をまとめたメモを残しておくことができます。
						</p>
					</div>
					<div class="col-12 col-md-4 order-sm-2">
						<img src="" alt="">
					</div>
				</div>

				<div class="mb-5 row">
					<div class="col-12 col-md-8 order-sm-2">
						<h3>こんなことができます</h3>
						<p>
							メモをmarkdown形式で残せます。論文のタイトルや著者、DOIと紐付けて保存できるため、後からでも簡単にメモを見つけることができます。
							もちろんスマホからでもアクセスできます。
						</p>
					</div>
					<div class="col-12 col-md-4 order-sm-1">
						<img src="" alt="">
					</div>
				</div>
			</div>
		</section>
	</main>
</div>